version: '2'
services:
    rns-app:
        image: rns
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rns-mysql:3306/rns?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rns-mysql:
        extends:
            file: mysql.yml
            service: rns-mysql
